# nginx ingress service
apiVersion: v1
kind: Service
metadata:
  name: private-nginx-ingress-lb
  namespace: kube-system
  labels:
    app: private-nginx-ingress-lb
  annotations:
    # set loadbalancer to the specified slb id
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-xxxx
    # set loadbalancer address type to intranet if using private slb instance
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: 'true'
spec:
  type: LoadBalancer
  # do not route traffic to other nodes
  # and reserve client ip for upstream
  externalTrafficPolicy: "Local"
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  selector:
    # select app=ingress-nginx pods
    app: private-ingress-nginx
---
# nginx config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: private-nginx-configuration
  namespace: kube-system
  labels:
    app: ingress-nginx
data:
    proxy-body-size: 20m
    proxy-connect-timeout: "10"
    max-worker-connections: "65536"
    enable-underscores-in-headers: "true"
    reuse-port: "true"
    worker-cpu-affinity: "auto"
    server-tokens: "false"
    ssl-redirect: "false"
    allow-backend-server-header: "true"
    ignore-invalid-headers: "true"
    generate-request-id: "true"
    #forwarded-for-header: "X-Real-IP"
    #compute-full-forwarded-for: "true"
    #hsts: "false"
    #enable-vts-status: "true"
    #use-proxy-protocol: "true"
---
# nginx tcp stream config map
kind: ConfigMap
apiVersion: v1
metadata:
  name: private-tcp-services
  namespace: kube-system
---
# nginx udp stream config map
kind: ConfigMap
apiVersion: v1
metadata:
  name: private-udp-services
  namespace: kube-system
---
# nginx ingress pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-nginx-ingress-controller
  labels:
    app: private-ingress-nginx
  namespace: kube-system
  annotations:
    component.version: '0.22.0'
    component.revision: '5'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: private-ingress-nginx
  template:
    metadata:
      labels:
        app: private-ingress-nginx
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
    spec:
      #tolerations:
      #  - key: node-role.kubernetes.io/master
      #    effect: NoSchedule
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ingress-nginx
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: nginx-ingress-controller
      initContainers:
      - name: init-sysctl
        image: registry-vpc.cn-hongkong.aliyuncs.com/acs/busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          sysctl -w net.core.somaxconn=65535
          sysctl -w net.ipv4.ip_local_port_range="1024 65535"
          sysctl -w fs.file-max=1048576
          sysctl -w fs.inotify.max_user_instances=16384
          sysctl -w fs.inotify.max_user_watches=524288
          sysctl -w fs.inotify.max_queued_events=16384
        securityContext:
          privileged: true
      containers:
      - name: nginx-ingress-controller
        image: registry-vpc.cn-hongkong.aliyuncs.com/acs/aliyun-ingress-controller:v0.22.0.5-552e0db-aliyun
        args:
          - /nginx-ingress-controller
          - --configmap=$(POD_NAMESPACE)/private-nginx-configuration
          - --tcp-services-configmap=$(POD_NAMESPACE)/private-tcp-services
          - --udp-services-configmap=$(POD_NAMESPACE)/private-udp-services
          - --annotations-prefix=nginx.ingress.kubernetes.io
          - --publish-service=$(POD_NAMESPACE)/private-nginx-ingress-lb
          - --ingress-class=private
          - --v=2
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          capabilities:
              drop:
              - ALL
              add:
              - NET_BIND_SERVICE
          runAsUser: 33
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
